dates:
  start: '2019-05-20 00:00:00'
  end: '2019-05-27 00:00:00'
timestep: 24 # in hours

# Arkansas River near Haskell, OK
# Using pkq_site.rds file from https://github.com/USGS-VIZLAB/vizstorm-GIF/blob/OklahomaFloods-2019/1_fetch/out/
# Plus cross-checking with NWS forecast table: https://www.nws.noaa.gov/oh/hads/USGS/OK_USGS-HADS_SITES.txt
nws_site: "HSKO2"
nwis_site: "07165570"

# Should create more elegant way to get min/max stage in the future
stage:
  min: 0
  max: 25

# animation options
animation:
  frame_rate: 4 #original input frames per second
  output_frame_rate: 9 #fps, but the actual frames in the video (not 1:1 with input)
