dates:
  start: '2019-12-20 00:00:00'
  end: '2020-01-01 00:00:00'
timestep: 12 # in hours

nws_site: "SRPW1"
nwis_site: "12061500"

# Should create more elegant way to get min/max stage in the future
stage:
  min: 0
  max: 25

# animation options
animation:
  frame_rate: 4 #original input frames per second
  output_frame_rate: 9 #fps, but the actual frames in the video (not 1:1 with input)
